###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class CategorizedProcess(BaseModel):
    process_id: Optional[str] = None
    process_name: Optional[str] = None
    unique_activities: List[str]
    category: Optional[str] = None

class ExtractedPairs(BaseModel):
    pairs_from_label: List["PairsFromLabel"]

class ObjectActionPair(BaseModel):
    object: Optional[str] = None
    action: Optional[str] = None

class PairsFromLabel(BaseModel):
    original_label: Optional[str] = None
    object_action_pairs: List["ObjectActionPair"]
